### ISSUE TITLE
Please help to use?

### ISSUE THREAD

**Issue by thearabbit** [vadimrostok/reactive-input#2]

**Comment by vadimrostok** [comment]
It was intended to implement simple two-way data binding for Meteor. This package is no longer maintained and I'm afraid I won't find time to even write some proper documentation for it. So I don't recommend to use it in production.
Though if you still want to try it, this is an example of its basic usage:

Template logic:

```
commentObject = new ReactiveVar { comment: "" }

Template.commentForm.helpers
  commentObjectVar: -> commentObject
```

Template view:

```
<template name="commentForm">
  {{> reactiveInput 
     input="text" 
     name="comment"
     reactiveModel=commentObjectVar 
     fieldName="comment"}}
```

After any change to "comment" input (generated by reactive-input) `commentObject` would be updated as well.

**Comment by thearabbit** [comment]
thank I will try.
